{application,
 dxcommon,
 [{description,"System Monitoring Commons Library"},
  {vsn,"0.0.1"},
  {modules,
   ['dxcommon.connect_time',
    'dxcommon.data',
    'dxcommon.datetime',
    'dxcommon.node_info',
    'dxcommon.string',
    'dxcommon.subscription',
    'dxcommon.user',
    dxcommon]},
  {registered,[]},
  {applications,[kernel,stdlib]},
  {env,[]}]}.