#!/usr/bin/env sh

## startup a development server

RUNNER_SCRIPT_DIR=$(cd ${0%/*} && pwd)
REL_DIR="$RUNNER_SCRIPT_DIR/release"
DEV_DIR="$RUNNER_SCRIPT_DIR/dev"
SYS="-sys $REL_DIR/setup/start"
BOOT="-boot $REL_DIR/setup/start"
CONFIG="-config $REL_DIR/files/app.config"
START_ARGS="$SYS $BOOT $CONFIG"
HOST=`hostname`
NAME="-name nw-dev@$HOST"

if [ ! -d "$DEV_DIR" ]; then
    echo "Setting up development environment for first time..."
    mkdir -p "$DEV_DIR/etc/db"
    mkdir -p "$DEV_DIR/log"
    cd "$DEV_DIR"
    SYS="-sys $REL_DIR/setup/install"
    BOOT="-boot $REL_DIR/setup/install"
    CONF="-config $REL_DIR/files/app.config"
    eval "erl $NAME $SYS $BOOT -embedded $CONF"
fi

cd "$DEV_DIR"

for var in "$@"
do
    case "$var" in
        --help)
            echo "$0 [options]"
            echo "--kit = start with dxkit"
            echo "--web = start with dxkit + webapp"
            exit 0
            ;;
        --kit)
            START_ARGS="$START_ARGS -eval 'dxkit:start_dev()'"
            ;;
        --web)
            START_ARGS="$START_ARGS -eval 'dxweb:start_dev()'"
            ;;
        --attach)
            ATTACHED=""
            ;;
        *)
            echo "Ignoring $var"
    esac
done

EXEC_CMD="erl $NAME -pa `pwd` $START_ARGS"
echo "$EXEC_CMD"
eval "$EXEC_CMD"

